POST http://localhost:8081
Content-Type: application/json

{
  "type": "stats"
}

###

POST http://localhost:8081
Content-Type: application/json

{
  "type": "keys",
  "id": "http://localhost",
  "key": "123456"
}

###
