name: Build

on:
  push:
    branches:
      - master
      - develop
      - dotnet

  release:
    types: [ published ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    if: github.repository == 'xibosignage/xibo-xmr'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Login
        run: |
          docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build Latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker build . -t ghcr.io/xibosignage/xibo-xmr:latest
          docker push ghcr.io/xibosignage/xibo-xmr:latest

      - name: Build Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build . -t ghcr.io/xibosignage/xibo-xmr:develop
          docker push ghcr.io/xibosignage/xibo-xmr:develop

      - name: Build Develop
        if: github.ref == 'refs/heads/dotnet'
        run: |
          docker build . -t ghcr.io/xibosignage/xibo-xmr:dotnet
          docker push ghcr.io/xibosignage/xibo-xmr:dotnet

      - name: Build Release
        if: github.event_name == 'release'
        run: |
          docker build . -t ghcr.io/xibosignage/xibo-xmr:${GITHUB_REF##*/}
          docker push ghcr.io/xibosignage/xibo-xmr:${GITHUB_REF##*/}
